variable "config_file" {}
variable "gcs_bucket" {}
variable "region" {}
variable "projet_name" {}
variable "cluster_name" {}
variable "machine_type" {}
variable "node_count" {}
variable "kubernetes_version" {}
variable "master_kubernetes_version" {}
